### ISSUE TITLE
SEO attribute not saved to database and then not pre filled too

### ISSUE THREAD

**Issue by sathishkurichy** [cwsdigital/twill-metadata#11]
![image](https://user-images.githubusercontent.com/14196371/138458638-2119925e-4a50-4fe5-a86c-52d8cc9e311e.png)

I've used latest version. Can you please check the screenshot and let me know suggestion for the issue.?

**Comment by chrispymm** [comment]
Hi, do you have the 'HandleMetadata' trait on your repository? 

That's what is responsible for taking the metadata fields and persisting them.

**Comment by chrispymm** [comment]
Hi, apologies, I've been away on holiday, so the above was a very quick response to your issue.

I noticed you asked some questions in the Twill discord, and received some support there. 

I'm going to close this issue, but if you have any further problems you can raise another issue, or feel free to post in the discord.
