### ISSUE TITLE
Settings page not saving

### ISSUE THREAD

**Issue by michaeljcoyne** [cwsdigital/twill-metadata#15]
Settings page is not saving the meta data

**Comment by pauldwight** [comment]
Hi @michaeljcoyne can you give some more context here please.

Which versions for:
* Laravel
* Twill
* cwsdigital/twill-metadata

Can you see the settings and setting_translations tables in your database? Do you have any other items being saved to the settings table that does work or are you not able to save anything to the settings table?

**Comment by pauldwight** [comment]
Closing due to lack of response.

**Comment by michaeljcoyne** [comment]
Twill 2.8.0 (did on 2.7 also)
Laravel  8.83.5
cwsdigital/twill-metadata 1.1

Just not saving on global settings

**Comment by pauldwight** [comment]
@michaeljcoyne are you using translated settings? If so - check out issue raised - https://github.com/area17/twill/issues/1572

**Comment by michaeljcoyne** [comment]
No I don't think so just out the box settings.

**Comment by csikoszoltan** [comment]
I have the same issue. I don't use translations.
Values are in the setting_translations table but they don't showing in the admin.

**Comment by AndreSchwarzer** [comment]
I'm not really using translations yet.

I just added a second language to `config/translatable.php`.

```php
<?php
    // ...

    'locales' => [
        'de',
        'en', // not used at the moment
    ],

   // ...
```

That did the trick for me.

**Comment by pauldwight** [comment]
See #20 for alternative way to use without translation
