### ISSUE TITLE
Global SEO settings not prefilled after save

### ISSUE THREAD

**Issue by csikoszoltan** [cwsdigital/twill-metadata#20]
Hello,

I just added your package to a fresh Laravel/Twill install and after saving anything in the Global Settings menu, it won't show in the form after refresh.
It's saved in the database (setting_translations table) and works on the models.
Is there anything I can do to make it work?

PHP 8.1
Twill 2.8.6

Thanks,
Zoli

**Comment by pauldwight** [comment]
@csikoszoltan currently this package assumes you are using translations (something we can look at to change in the future).

You can publish the views and change the translated option for each formField from true to false.

```
php artisan vendor:publish --provider="CwsDigital\TwillMetadata\TwillMetadataServiceProvider" --tag=views
```

Then edit the resources/vendor/twill-metadata/includes/*.blade.php and change references to 'translated' to false.

E.g. so your resources/vendor/twill-metadata/includes/metadata-settings.blade.php should look like this.
```php
@formField('input', [
    'name' => 'site_title',
    'label' => twillTrans('twill-metadata::settings.fields.site_title.label'),
    'note' => twillTrans('twill-metadata::settings.fields.site_title.note'),
    'textLimit' => '80',
    'translated' => false,
])

@formField('medias', [
    'name' => 'default_social_image',
    'label' => twillTrans('twill-metadata::settings.fields.og_image.label'),
    'translated' => false,
])

@formField('input', [
    'name' => 'site_twitter',
    'label' => twillTrans('twill-metadata::settings.fields.twitter_handle.label'),
    'note' => twillTrans('twill-metadata::settings.fields.twitter_handle.note'),
    'textLimit' => '80',
    'translated' => false,
])

```

**Comment by csikoszoltan** [comment]
Thanks, works this way!
Meanwhile I tested with translations and I'm getting the values there too.
