### ISSUE TITLE
Missing content from readme

### ISSUE THREAD

**Issue by MDylan** [cwsdigital/twill-metadata#22]
Twill 2.12.4

Follow the current readme, I have an error on settings page.
I can't crop the social image, there is an error message in console.

I figured out this solution ([based on this](https://github.com/area17/twill/discussions/977#discussioncomment-875443))

Paste the following line into **twill.php**
```
return [
...
    'settings' => [
        'crops' => [
            'default_social_image' => [
                'default' => [
                    [
                        'name' => 'default',
                        'ratio' => 1.91 / 1,
                        'minValues' => [
                            'width' => 1200,
                            'height' => 627,
                        ],
                    ],
                ],

            ],
        ],
    ],
...
];
```

I hope it will help to somebody.

**Comment by pauldwight** [comment]
Thanks @MDylan readme has been updated with the latest update
