### ISSUE TITLE
Error Found Due to Missing Social Sharing Image While Displaying Page

### ISSUE THREAD

**Issue by abidkhan484** [cwsdigital/twill-metadata#29]
When a page is rendered without specifying a social sharing image, it results in an error. This could potentially disrupt the page's display.

While trying to use it in the front end according to the [Readme](https://github.com/cwsdigital/twill-metadata?tab=readme-ov-file#how-to-use-metatags-in-your-frontend-code), it shows the error below. 

![image](https://github.com/user-attachments/assets/ec7bdb2d-75a3-4b6f-a7bb-ab816f865980)

**Note: It's working fine if the image is being uploaded in the social image section. There's no error in the display**

**Comment by abidkhan484** [comment]
It would be helpful if you could share any clues to fix it.

@pauldwight

**Comment by pauldwight** [comment]
> It would be helpful if you could share any clues to fix it.
> 
> @pauldwight

Without more information I can't help. Have you set-up your controller correctly? What does your model look like with the Metadata traits etc. What version are you using?

**Comment by abidkhan484** [comment]
> > It would be helpful if you could share any clues to fix it.
> > @pauldwight
> 
> Without more information I can't help. Have you set-up your controller correctly? What does your model look like with the Metadata traits etc. What version are you using?

**Twill version: 3.4.1**
For the controller and model, I have done the minimalistic setup that is shared in the [Configuration Readme](https://github.com/cwsdigital/twill-metadata?tab=readme-ov-file#configuration). nothing additional I need right now.

Pastebin(expire in 21 days): https://paste.mozilla.org/0Cma9qxJ

FYI, @pauldwight

**Comment by pauldwight** [comment]
> > > It would be helpful if you could share any clues to fix it.
> > > @pauldwight
> > 
> > 
> > Without more information I can't help. Have you set-up your controller correctly? What does your model look like with the Metadata traits etc. What version are you using?
> 
> **Twill version: 3.4.1** For the controller and model, I have done the minimalistic setup that is shared in the [Configuration Readme](https://github.com/cwsdigital/twill-metadata?tab=readme-ov-file#configuration). nothing additional I need right now.
> 
> Pastebin(expire in 21 days): https://paste.mozilla.org/0Cma9qxJ
> 
> FYI, @pauldwight

@abidkhan484 and the controller for your frontend?

**Comment by abidkhan484** [comment]
@pauldwight, It's been failed in [this line](https://github.com/cwsdigital/twill-metadata/blob/v1.x/src/Traits/SetsMetadata.php#L32). 

**Possible solution:** Using a try-catch can fix it.


> > **Twill version: 3.4.1** For the controller and model, I have done the minimalistic setup that is shared in the [Configuration Readme](https://github.com/cwsdigital/twill-metadata?tab=readme-ov-file#configuration). nothing additional I need right now.
> > Pastebin(expire in 21 days): https://paste.mozilla.org/0Cma9qxJ
> > FYI, @pauldwight
> 
> @abidkhan484 and the controller for your frontend?

The frontend controller is also pretty simple according to the documentation.

**Pastebin with display controller (expire in 21 days):** https://paste.mozilla.org/BquHQO1s

If the social image of the below field is set, then no error occurs.

![image](https://github.com/user-attachments/assets/eed527d0-25e7-4e10-b314-e17ad23f864b)

**Comment by dancing-janissary** [comment]
@pauldwight  @abidkhan484  It appears that if you save SEO settings once, it will set a default image as null. Then even if your modules data has null image, it won't be a problem. However, when I try to upload an image via twill setting (and I have crop parameters set in my config) the following error is thrown:
![Screenshot 2024-11-14 at 17 55 39](https://github.com/user-attachments/assets/4d54d67a-d969-4a22-b966-2e807f774f94)
`{
    "message": "Undefined array key \"default_social_image\"",
    "exception": "ErrorException",
    "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/BlockRepository.php",
    "line": 31,
    "trace": [
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",
            "line": 255,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/BlockRepository.php",
            "line": 31,
            "function": "Illuminate\\Foundation\\Bootstrap\\{closure}",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/Behaviors/HandleMedias.php",
            "line": 99,
            "function": "getCrops",
            "class": "A17\\Twill\\Repositories\\BlockRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php",
            "line": 240,
            "function": "A17\\Twill\\Repositories\\Behaviors\\{closure}",
            "class": "A17\\Twill\\Repositories\\BlockRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/Behaviors/HandleMedias.php",
            "line": 114,
            "function": "each",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/Behaviors/HandleMedias.php",
            "line": 58,
            "function": "getMedias",
            "class": "A17\\Twill\\Repositories\\BlockRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/ModuleRepository.php",
            "line": 510,
            "function": "afterSaveHandleMedias",
            "class": "A17\\Twill\\Repositories\\BlockRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/BlockRepository.php",
            "line": 68,
            "function": "afterSave",
            "class": "A17\\Twill\\Repositories\\ModuleRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/ModuleRepository.php",
            "line": 239,
            "function": "afterSave",
            "class": "A17\\Twill\\Repositories\\BlockRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php",
            "line": 30,
            "function": "A17\\Twill\\Repositories\\{closure}",
            "class": "A17\\Twill\\Repositories\\ModuleRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php",
            "line": 509,
            "function": "transaction",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 355,
            "function": "__call",
            "class": "Illuminate\\Database\\DatabaseManager",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/ModuleRepository.php",
            "line": 242,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/Behaviors/HandleBlocks.php",
            "line": 163,
            "function": "update",
            "class": "A17\\Twill\\Repositories\\ModuleRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/Behaviors/HandleBlocks.php",
            "line": 148,
            "function": "updateBlock",
            "class": "A17\\Twill\\Repositories\\AppSettingsRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/Behaviors/HandleBlocks.php",
            "line": 124,
            "function": "updateOrCreateBlock",
            "class": "A17\\Twill\\Repositories\\AppSettingsRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/ModuleRepository.php",
            "line": 510,
            "function": "afterSaveHandleBlocks",
            "class": "A17\\Twill\\Repositories\\AppSettingsRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/ModuleRepository.php",
            "line": 239,
            "function": "afterSave",
            "class": "A17\\Twill\\Repositories\\ModuleRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php",
            "line": 30,
            "function": "A17\\Twill\\Repositories\\{closure}",
            "class": "A17\\Twill\\Repositories\\ModuleRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php",
            "line": 509,
            "function": "transaction",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 355,
            "function": "__call",
            "class": "Illuminate\\Database\\DatabaseManager",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Repositories/ModuleRepository.php",
            "line": 242,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php",
            "line": 1349,
            "function": "update",
            "class": "A17\\Twill\\Repositories\\ModuleRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php",
            "line": 1286,
            "function": "performUpdate",
            "class": "A17\\Twill\\Http\\Controllers\\Admin\\ModuleController",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Controllers/Admin/AppSettingsController.php",
            "line": 42,
            "function": "update",
            "class": "A17\\Twill\\Http\\Controllers\\Admin\\ModuleController",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "update",
            "class": "A17\\Twill\\Http\\Controllers\\Admin\\AppSettingsController",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 43,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 260,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 205,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 806,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 144,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php",
            "line": 416,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 165,
            "function": "A17\\Twill\\Http\\Controllers\\Admin\\{closure}",
            "class": "A17\\Twill\\Http\\Controllers\\Admin\\ModuleController",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Middleware/Localization.php",
            "line": 22,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "A17\\Twill\\Http\\Middleware\\Localization",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Middleware/ValidateBackHistory.php",
            "line": 17,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "A17\\Twill\\Http\\Middleware\\ValidateBackHistory",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Middleware/Impersonate.php",
            "line": 32,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "A17\\Twill\\Http\\Middleware\\Impersonate",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 50,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/area17/twill/src/Http/Middleware/Authenticate.php",
            "line": 32,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "A17\\Twill\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 78,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 121,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 64,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 67,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 119,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 807,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 784,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 748,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 737,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 200,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 144,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php",
            "line": 40,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php",
            "line": 99,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Http\\Middleware\\HandleCors",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php",
            "line": 39,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Http\\Middleware\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 119,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 175,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 144,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/olmadikprojeler.com/golive.olmadikprojeler.com/public/index.php",
            "line": 52,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}`

**Comment by abidkhan484** [comment]
> "message": "Undefined array key \"default_social_image\""

@Exarillion, Which twill version are you using? I didn't get this issue with Twill 3.4.1. [Using this setting](https://github.com/cwsdigital/twill-metadata?tab=readme-ov-file#1--make-sure-the-default-social-media-image-crop-is-in-your-twillphp-config) may help you to solve this.

**Comment by abidkhan484** [comment]
> @pauldwight, It's been failed in [this line](https://github.com/cwsdigital/twill-metadata/blob/v1.x/src/Traits/SetsMetadata.php#L32).
> 
> **Possible solution:** Using a try-catch can fix it.
> 
> > > **Twill version: 3.4.1** For the controller and model, I have done the minimalistic setup that is shared in the [Configuration Readme](https://github.com/cwsdigital/twill-metadata?tab=readme-ov-file#configuration). nothing additional I need right now.
> > > Pastebin(expire in 21 days): https://paste.mozilla.org/0Cma9qxJ
> > > FYI, @pauldwight
> > 
> > 
> > @abidkhan484 and the controller for your frontend?
> 
> The frontend controller is also pretty simple according to the documentation.
> 
> **Pastebin with display controller (expire in 21 days):** https://paste.mozilla.org/BquHQO1s
> 
> If the social image of the below field is set, then no error occurs.
> 
> ![image](https://private-user-images.githubusercontent.com/15053047/385115584-eed527d0-25e7-4e10-b314-e17ad23f864b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjI0MjcsIm5iZiI6MTczMTY2MjEyNywicGF0aCI6Ii8xNTA1MzA0Ny8zODUxMTU1ODQtZWVkNTI3ZDAtMjVlNy00ZTEwLWIzMTQtZTE3YWQyM2Y4NjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA5MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZmVkODVhMDY1OWQ3MWIwYThiOThmNmE2ZGIyMjYyNTc2ZjA3MmNlZGExZmU5NzIxNjI4NjRiZDA2Mzc1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ShGLTiXntpS5mErTagaVZ4rjs4rPhVIWrRsP3gE9LBs)



Finally, I solved this without the try-catch mentioned above and by adding this metadata config in `config/metadata.php`
 with following from [this code](https://github.com/cwsdigital/twill-metadata/blob/v1.x/src/Models/Behaviours/HasMetadata.php#L23) to [this section](https://github.com/cwsdigital/twill-metadata/blob/v1.x/src/Models/Behaviours/HasMetadata.php#L37C1-L42C77).

`````````````````````sh

diff --git a/config/metadata.php b/config/metadata.php
index 6c6fcaa..f45cb9f 100644
--- a/config/metadata.php
+++ b/config/metadata.php
@@ -6,6 +6,10 @@
         'title' => 'title',
         'description' => false,
         'og_type' => 'metadataDefaultOgType',
+        'og_image' => [
+            'role' => '',
+            'crop' => '',
+        ],
         'card_type' => 'metadataDefaultCardType',
     ],

**Comment by pauldwight** [comment]
@Exarillion I think you are talking about something different. Try adding the below into your config/twill.php config file

```php
'block_editor' => [
        'use_twill_blocks' => [],
        'crops' => [
            'default_social_image' => [
                'default' => [
                    [
                        'name' => 'default',
                        'ratio' => 1.91 / 1,
                        'minValues' => [
                            'width' => 1200,
                            'height' => 627,
                        ],
                    ],
                ],
            ],
        ],
    ],
```
