### ISSUE TITLE
Default medias Param is being conflicted for inserting the data

### ISSUE THREAD

**Issue by abidkhan484** [cwsdigital/twill-metadata#30]
**Root Cause:**
The issue is caused by the initializeHasMetadata method, particularly in the [HasMetadata.php](https://github.com/cwsdigital/twill-metadata/blob/v1.x/src/Models/Behaviours/HasMetadata.php#L82C1-L86C10) section. When the mediasParams are being added, it interferes with the process of adding only the title field, which leads to an error when additional information is missing.

**Error Details:** The error is triggered when the framework attempts to run a database query, and it expects an array, but a string is provided instead. This happens in the [Illuminate/Query/Grammers/Grammer.php](https://github.com/illuminate/database/blob/master/Query/Grammars/Grammar.php#L1174) file of the Laravel framework.

```sh
{
    "message": "Illuminate\\Database\\Grammar::parameterize(): Argument #1 ($values) must be of type array, string given, called in /zero/projects/fusion/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 1181",
    "exception": "TypeError",
    "file": "/zero/projects/fusion/vendor/laravel/framework/src/Illuminate/Database/Grammar.php",
    "line": 197,
    "trace": [
        {
            "file": "/zero/projects/fusion/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php",
            "line": 1181,
            "function": "parameterize",
            "class": "Illuminate\\Database\\Grammar",
            "type": "->"
        },
        {
            "function": "Illuminate\\Database\\Query\\Grammars\\{closure}",
            "class": "Illuminate\\Database\\Query\\Grammars\\Grammar",
            "type": "->"
        },
        {
            "file": "/zero/projects/fusion/vendor/laravel/framework/src/Illuminate/Collections/Arr.php",
            "line": 605,
            "function": "array_map"
        },
```

**Comment by pauldwight** [comment]
This is usually because your model doesn't have any defined mediaParams?

If it doesn't then define some mediaParams for the model.

```php
public $mediasParams = [
        'cover' => [
            'default' => [
                [
                    'name' => 'default',
                    'ratio' => 16 / 9,
                ],
            ],
        ],
    ];

```

**Comment by abidkhan484** [comment]
> This is usually because your model doesn't have any defined mediaParams?
> 
> If it doesn't then define some mediaParams for the model.
> 
> ```
> public $mediasParams = [
>         'cover' => [
>             'default' => [
>                 [
>                     'name' => 'default',
>                     'ratio' => 16 / 9,
>                 ],
>             ],
>         ],
>     ];
> ```

Hi @pauldwight, It's working after adding the attribute in the model. I have 2 observations.

1. I have set the same in the metadata config with cover key, but it still didn't work. So, do I need to add the same attribute in all the models?
2. It would be better to add this in the readme.

Thanks for the prompt support.
